
%MACRO TABLE_POP (V1=, V2=, V3=, V4=);

DATA &V1;
SET &V1;

OUTPUT;
TRT01P = "Overall";
TRT01PN = 5;
OUTPUT;
KEEP USUBJID TRT01P TRT01PN SAFFL;
RUN;

DATA &V1;
SET &V1;
IF TRT01PN NE .;
RUN;


PROC SQL NOPRINT;
CREATE TABLE TRT AS
SELECT TRT01PN, TRT01P, COUNT(DISTINCT USUBJID) AS DENOM FROM &V1
GROUP BY TRT01PN, TRT01P
ORDER BY TRT01PN, TRT01P;

PROC SQL NOPRINT;
CREATE TABLE TRT1 AS
SELECT *,
	D2.TRT01PN AS TRT01PN_,
	D2.TRT01P AS TRT01P_
FROM TRT AS D1
RIGHT JOIN TRT01PN_DATA AS D2
ON D1.TRT01PN = D2.TRT01PN;
QUIT;

DATA TRT2;
SET TRT1;
IF TRT01PN =. THEN TRT01PN=TRT01PN_;
IF DENOM=. THEN DENOM=0;
IF TRT01P ="" THEN TRT01P=TRT01P_;
DROP TRT01PN_ TRT01P_;
RUN;

PROC SQL NOPRINT;
SELECT DENOM INTO: n1 -:n5 FROM TRT2;
QUIT;

PROC SQL NOPRINT;
CREATE TABLE SAF1 AS
SELECT TRT01PN, COUNT(DISTINCT USUBJID) AS NN,
"&V3" AS POP LENGTH=100,&V4 AS SQ FROM &V1
WHERE SAFFL = "Y"
GROUP BY TRT01PN
ORDER BY TRT01PN;
QUIT;


PROC SQL NOPRINT;
CREATE TABLE SAF2 AS
SELECT *,
	D2.TRT01PN AS TRT01PN_,
	D2.DENOM
FROM SAF1 AS D1
RIGHT JOIN TRT2 AS D2
ON D1.TRT01PN = D2.TRT01PN;
QUIT;

DATA SAF3;
SET SAF2;
IF TRT01PN =. THEN TRT01PN = TRT01PN_;
IF NN =. THEN NN=DENOM;
IF POP ="" THEN POP="&V3";
IF SQ = . THEN SQ = &V4;
DROP TRT01P TRT01PN_ DENOM;
RUN;

DATA FINAL1;
SET SAF3;
LENGTH GRPA_1 $20.;

IF TRT01PN=1 THEN DO;
	IF NN=. OR NN=0 THEN GRPA_1="0";
ELSE IF NN=&n1 THEN GRPA_1=PUT(NN,3.)||" (100)";
ELSE GRPA_1=PUT(NN,3.)||" ("||PUT(NN/&n1*100,4.1)||")";
END;

IF TRT01PN=2 THEN DO;
	IF NN=. OR NN=0 THEN GRPA_1="0";
ELSE IF NN=&n2 THEN GRPA_1=PUT(NN,3.)||" (100)";
ELSE GRPA_1=PUT(NN,3.)||" ("||PUT(NN/&n2*100,4.1)||")";
END;

IF TRT01PN=3 THEN DO;
	IF NN=. OR NN=0 THEN GRPA_1="0";
ELSE IF NN=&n3 THEN GRPA_1=PUT(NN,3.)||" (100)";
ELSE GRPA_1=PUT(NN,3.)||" ("||PUT(NN/&n3*100,4.1)||")";
END;

IF TRT01PN=4 THEN DO;
	IF NN=. OR NN=0 THEN GRPA_1="0";
ELSE IF NN=&n4 THEN GRPA_1=PUT(NN,3.)||" (100)";
ELSE GRPA_1=PUT(NN,3.)||" ("||PUT(NN/&n4*100,4.1)||")";
END;

IF TRT01PN=5 THEN DO;
	IF NN=. OR NN=0 THEN GRPA_1="0";
ELSE IF NN=&n5 THEN GRPA_1=PUT(NN,3.)||" (100)";
ELSE GRPA_1=PUT(NN,3.)||" ("||PUT(NN/&n5*100,4.1)||")";
END;

RUN;

PROC SORT DATA=FINAL1;
BY SQ POP;
RUN;

PROC TRANSPOSE DATA=FINAL1 OUT=ALL_ PREFIX=t;
BY SQ POP;
ID TRT01PN;
VAR GRPA_1;
RUN;

DATA &V2;
SET ALL_;
STAT="n (%)";
RUN;

%MEND;

%MACRO TABLE_POP_1 (V1=, V2=, V3=, V4=, V5=);

DATA &V1;
SET &V1;

OUTPUT;
TRT01P = "Overall";
TRT01PN = 5;
OUTPUT;
KEEP USUBJID TRT01P TRT01PN SAFFL;
RUN;

DATA &V1;
SET &V1;
IF TRT01PN NE .;
RUN;


PROC SQL NOPRINT;
CREATE TABLE TRT AS
SELECT TRT01PN, TRT01P, COUNT(DISTINCT USUBJID) AS DENOM FROM &V5
GROUP BY TRT01PN, TRT01P
ORDER BY TRT01PN, TRT01P;

PROC SQL NOPRINT;
CREATE TABLE TRT1 AS
SELECT *,
	D2.TRT01PN AS TRT01PN_,
	D2.TRT01P AS TRT01P_
FROM TRT AS D1
RIGHT JOIN TRT01PN_DATA AS D2
ON D1.TRT01PN = D2.TRT01PN;
QUIT;

DATA TRT2;
SET TRT1;
IF TRT01PN =. THEN TRT01PN=TRT01PN_;
IF DENOM=. THEN DENOM=0;
IF TRT01P ="" THEN TRT01P=TRT01P_;
DROP TRT01PN_ TRT01P_;
RUN;

PROC SQL NOPRINT;
SELECT DENOM INTO: n1 -:n5 FROM TRT2;
QUIT;

PROC SQL NOPRINT;
CREATE TABLE SAF1 AS
SELECT TRT01PN, COUNT(DISTINCT USUBJID) AS NN,
"&V3" AS POP LENGTH=100,&V4 AS SQ FROM &V1
WHERE SAFFL = "Y"
GROUP BY TRT01PN
ORDER BY TRT01PN;
QUIT;


PROC SQL NOPRINT;
CREATE TABLE SAF2 AS
SELECT *,
	D2.TRT01PN AS TRT01PN_,
	D2.DENOM
FROM SAF1 AS D1
RIGHT JOIN TRT2 AS D2
ON D1.TRT01PN = D2.TRT01PN;
QUIT;

DATA SAF3;
SET SAF2;
IF TRT01PN =. THEN TRT01PN = TRT01PN_;
IF NN =. THEN NN=0;
IF POP ="" THEN POP="&V3";
IF SQ = . THEN SQ = &V4;
DROP TRT01P TRT01PN_ DENOM;
RUN;

DATA FINAL1;
SET SAF3;
LENGTH GRPA_1 $20.;

IF TRT01PN=1 THEN DO;
	IF NN=. OR NN=0 THEN GRPA_1="0";
ELSE IF NN=&n1 THEN GRPA_1=PUT(NN,3.)||" (100)";
ELSE GRPA_1=PUT(NN,3.)||" ("||PUT(NN/&n1*100,4.1)||")";
END;

IF TRT01PN=2 THEN DO;
	IF NN=. OR NN=0 THEN GRPA_1="0";
ELSE IF NN=&n2 THEN GRPA_1=PUT(NN,3.)||" (100)";
ELSE GRPA_1=PUT(NN,3.)||" ("||PUT(NN/&n2*100,4.1)||")";
END;

IF TRT01PN=3 THEN DO;
	IF NN=. OR NN=0 THEN GRPA_1="0";
ELSE IF NN=&n3 THEN GRPA_1=PUT(NN,3.)||" (100)";
ELSE GRPA_1=PUT(NN,3.)||" ("||PUT(NN/&n3*100,4.1)||")";
END;

IF TRT01PN=4 THEN DO;
	IF NN=. OR NN=0 THEN GRPA_1="0";
ELSE IF NN=&n4 THEN GRPA_1=PUT(NN,3.)||" (100)";
ELSE GRPA_1=PUT(NN,3.)||" ("||PUT(NN/&n4*100,4.1)||")";
END;

IF TRT01PN=5 THEN DO;
	IF NN=. OR NN=0 THEN GRPA_1="0";
ELSE IF NN=&n5 THEN GRPA_1=PUT(NN,3.)||" (100)";
ELSE GRPA_1=PUT(NN,3.)||" ("||PUT(NN/&n5*100,4.1)||")";
END;

RUN;

PROC SORT DATA=FINAL1;
BY SQ POP;
RUN;

PROC TRANSPOSE DATA=FINAL1 OUT=ALL_ PREFIX=t;
BY SQ POP;
ID TRT01PN;
VAR GRPA_1;
RUN;

DATA &V2;
SET ALL_;
STAT="n (%)";
RUN;

%MEND;

%PUT "Use this MACRO: %TABLE_POP(V1=ADSL_safety, V2=FINAL_safety, V3=Safety Population, V4=1);";

